INSERT INTO public.option_definition (entity_type,category,feature_number,code,description,template_required,hand_required,pdf_pages,notes) VALUES
('door','Series','3','H','Honeycomb core, lockseam/full-flush; HF adds seamless tack-and-fill edge',false,false,'14-15, 29',NULL),
('door','Series','3','HF','Honeycomb core, lockseam/full-flush; HF adds seamless tack-and-fill edge',false,false,'14-15, 29',NULL),
('door','Series','3','HP','Polystyrene core, lockseam/full-flush; HPF seamless',false,false,'14-15, 29',NULL),
('door','Series','3','HPF','Polystyrene core, lockseam/full-flush; HPF seamless',false,false,'14-15, 29',NULL),
('door','Series','3','HT','Polyurethane core, lockseam/full-flush; HTF seamless',false,false,'14-15, 29',NULL),
('door','Series','3','HTF','Polyurethane core, lockseam/full-flush; HTF seamless',false,false,'14-15, 29',NULL),
('door','Series','3','HR','Temperature-rise core, lockseam/full-flush; HRF seamless',false,false,'14-15, 29','Non-flush temperature-rise doors have an additional adder.'),
('door','Series','3','HRF','Temperature-rise core, lockseam/full-flush; HRF seamless',false,false,'14-15, 29','Non-flush temperature-rise doors have an additional adder.'),
('door','Series','3','CH','Continuous-weld seamless glued-core series',false,false,'16-17, 29',NULL),
('door','Series','3','CHP','Continuous-weld seamless glued-core series',false,false,'16-17, 29',NULL),
('door','Series','3','CHT','Continuous-weld seamless glued-core series',false,false,'16-17, 29',NULL),
('door','Series','3','CHR','Continuous-weld seamless glued-core series',false,false,'16-17, 29',NULL),
('door','Series','3','LW','Steel-stiffened lockseam; LWF seamless',false,false,'18-19, 29',NULL),
('door','Series','3','LWF','Steel-stiffened lockseam; LWF seamless',false,false,'18-19, 29',NULL),
('door','Series','3','C','Continuous-weld seamless steel-stiffened door',false,false,'20-21, 29',NULL),
('door','Series','3','EH','Embossed lockseam honeycomb or polystyrene door; F suffix seamless',false,false,'22-23, 29',NULL),
('door','Series','3','EHF','Embossed lockseam honeycomb or polystyrene door; F suffix seamless',false,false,'22-23, 29',NULL),
('door','Series','3','EP','Embossed lockseam honeycomb or polystyrene door; F suffix seamless',false,false,'22-23, 29',NULL),
('door','Series','3','EPF','Embossed lockseam honeycomb or polystyrene door; F suffix seamless',false,false,'22-23, 29',NULL),
('door','Specialty series','3','W50','Piocane windstorm door',false,true,'89-91',NULL),
('door','Specialty series','3','W70','Piocane windstorm door',false,true,'89-91',NULL),
('door','Specialty series','3','FEMA','FEMA 361 C-series door',false,true,'94-95',NULL),
('door','Specialty series','3','STC','Piosonic sound-rated complete unit',false,true,'96-97',NULL),
('door','Specialty series','3','SBR','Blast-resistant or bullet-resistant door',false,true,'98-101',NULL),
('door','Specialty series','3','BR752','Blast-resistant or bullet-resistant door',false,true,'98-101',NULL),
('door','Gauge','4','18','Door face-sheet gauge',false,false,'29',NULL),
('door','Gauge','4','16','Door face-sheet gauge',false,false,'29',NULL),
('door','Gauge','4','14','Door face-sheet gauge',false,false,'29',NULL),
('door','Gauge','4','12','Door face-sheet gauge',false,false,'29',NULL),
('door','Material','5','C','Cold rolled steel / galvannealed',false,false,'29',NULL),
('door','Material','5','G','Cold rolled steel / galvannealed',false,false,'29',NULL),
('door','Thickness','6','4','1-3/4 / 1-3/8 / special thickness',false,false,'29',NULL),
('door','Thickness','6','8','1-3/4 / 1-3/8 / special thickness',false,false,'29',NULL),
('door','Thickness','6','T2','1-3/4 / 1-3/8 / special thickness',false,false,'29',NULL),
('door','Activity','7','SNGL','Single-opening leaf / standard-pair leaf / double-egress leaf',false,true,'30',NULL),
('door','Activity','7','PAIR','Single-opening leaf / standard-pair leaf / double-egress leaf',false,true,'30',NULL),
('door','Activity','7','DBLE','Single-opening leaf / standard-pair leaf / double-egress leaf',false,true,'30',NULL),
('door','Astragal','8','N','No astragal',false,false,'30',NULL),
('door','Astragal','8','ZS','Z astragal screw-applied / welded / shipped loose',false,true,'30',NULL),
('door','Astragal','8','ZW','Z astragal screw-applied / welded / shipped loose',false,true,'30',NULL),
('door','Astragal','8','ZL','Z astragal screw-applied / welded / shipped loose',false,true,'30',NULL),
('door','Astragal','8','FS','Flat astragal screw-applied / welded / shipped loose',false,true,'30',NULL),
('door','Astragal','8','FW','Flat astragal screw-applied / welded / shipped loose',false,true,'30',NULL),
('door','Astragal','8','FL','Flat astragal screw-applied / welded / shipped loose',false,true,'30',NULL),
('door','Elevation','9','F','Flush door faces',false,false,'30',NULL),
('door','Lite','9','V','Standard 10x10 vision lite / special vision lite',false,false,'30',NULL),
('door','Lite','9','SK','Standard 10x10 vision lite / special vision lite',false,false,'30',NULL),
('door','Lite','9','N3','Standard narrow-lite sizes',false,false,'30',NULL),
('door','Lite','9','N4','Standard narrow-lite sizes',false,false,'30',NULL),
('door','Lite','9','N5','Standard narrow-lite sizes',false,false,'30',NULL),
('door','Lite','9','NG68','6x30 / 6x34 narrow-glass kits',false,false,'30',NULL),
('door','Lite','9','NG70','6x30 / 6x34 narrow-glass kits',false,false,'30',NULL),
('door','Lite','9','G68','22x30 / 22x34 half-glass kits',false,false,'31',NULL),
('door','Lite','9','G70','22x30 / 22x34 half-glass kits',false,false,'31',NULL),
('door','Lite','9','FG68','22x60 / 22x64 full-glass kits',false,false,'31',NULL),
('door','Lite','9','FG70','22x60 / 22x64 full-glass kits',false,false,'31',NULL),
('door','Embossed lite','9','VE','Lite-kit patterns aligned to embossed panels',false,true,'31',NULL),
('door','Embossed lite','9','V2E','Lite-kit patterns aligned to embossed panels',false,true,'31',NULL),
('door','Embossed lite','9','NGE','Lite-kit patterns aligned to embossed panels',false,true,'31',NULL),
('door','Embossed lite','9','2NG','Lite-kit patterns aligned to embossed panels',false,true,'31',NULL),
('door','Embossed lite','9','GE','Lite-kit patterns aligned to embossed panels',false,true,'31',NULL),
('door','Embossed lite','9','GE1','Lite-kit patterns aligned to embossed panels',false,true,'31',NULL),
('door','Louver','9','L1','12x12 / 24x12 / 24x24 / special / UL-classified louver',false,false,'32',NULL),
('door','Louver','9','L2','12x12 / 24x12 / 24x24 / special / UL-classified louver',false,false,'32',NULL),
('door','Louver','9','L3','12x12 / 24x12 / 24x24 / special / UL-classified louver',false,false,'32',NULL),
('door','Louver','9','SK','12x12 / 24x12 / 24x24 / special / UL-classified louver',false,false,'32',NULL),
('door','Louver','9','L','12x12 / 24x12 / 24x24 / special / UL-classified louver',false,false,'32',NULL),
('door','Special size','10-11','SW','Special width / special height',false,false,'32-33',NULL),
('door','Special size','10-11','SH','Special width / special height',false,false,'32-33',NULL),
('door','Lock prep','12','MP','Multipurpose blank face with Government 86 edge',false,false,'34',NULL),
('door','Lock prep','12','MST','Mortise lock with sectional trim',true,true,'34',NULL),
('door','Lock prep','12','CRLP','Card-reader mortise / dual / cylindrical preparation',true,true,'34',NULL),
('door','Lock prep','12','CRDP','Card-reader mortise / dual / cylindrical preparation',true,true,'34',NULL),
('door','Lock prep','12','CRL2','Card-reader mortise / dual / cylindrical preparation',true,true,'34',NULL),
('door','Lock prep','12','CYL','Cylindrical family preparations',false,false,'34',NULL),
('door','Lock prep','12','CBF','Cylindrical family preparations',false,false,'34',NULL),
('door','Lock prep','12','CBE','Cylindrical family preparations',false,false,'34',NULL),
('door','Lock prep','12','T','Cylindrical family preparations',false,false,'34',NULL),
('door','Lock prep','12','L','Cylindrical family preparations',false,false,'34',NULL),
('door','Lock prep','12','ICL2','Interconnected lock within 7-inch centerline spacing',true,true,'34',NULL),
('door','Special lock prep','12','90U','Unit lock, push-pull, flush pull, multipoint, dummy trim, edge pull',true,false,'34',NULL),
('door','Special lock prep','12','PP','Unit lock, push-pull, flush pull, multipoint, dummy trim, edge pull',true,false,'34',NULL),
('door','Special lock prep','12','FP','Unit lock, push-pull, flush pull, multipoint, dummy trim, edge pull',true,false,'34',NULL),
('door','Special lock prep','12','3PTL','Unit lock, push-pull, flush pull, multipoint, dummy trim, edge pull',true,false,'34',NULL),
('door','Special lock prep','12','DTRP','Unit lock, push-pull, flush pull, multipoint, dummy trim, edge pull',true,false,'34',NULL),
('door','Special lock prep','12','EP','Unit lock, push-pull, flush pull, multipoint, dummy trim, edge pull',true,false,'34',NULL),
('door','Exit reinforcement','12','RP','Reinforcement-only exit-device families',false,true,'34',NULL),
('door','Exit reinforcement','12','SVR','Reinforcement-only exit-device families',false,true,'34',NULL),
('door','Exit reinforcement','12','RBA','Reinforcement-only exit-device families',false,true,'34',NULL),
('door','Exit reinforcement','12','RBI','Reinforcement-only exit-device families',false,true,'34',NULL),
('door','Exit reinforcement','12','MPAN','Reinforcement-only exit-device families',false,true,'34',NULL),
('door','Exit reinforcement','12','RMP','Reinforcement-only exit-device families',false,true,'34',NULL),
('door','Exit prep','12','RPP','Prepared exit-device families',true,true,'34',NULL),
('door','Exit prep','12','SVRP','Prepared exit-device families',true,true,'34',NULL),
('door','Exit prep','12','CVR','Prepared exit-device families',true,true,'34',NULL),
('door','Exit prep','12','MPNP','Prepared exit-device families',true,true,'34',NULL),
('door','Exit prep','12','RED','Prepared exit-device families',true,true,'34',NULL),
('door','Exit prep','12','SPL','Prepared exit-device families',true,true,'34',NULL),
('door','Primary strike','12','478','Inactive-leaf strike preparations',false,true,'34',NULL),
('door','Primary strike','12','234','Inactive-leaf strike preparations',false,true,'34',NULL),
('door','Primary strike','12','ESTK','Inactive-leaf strike preparations',false,true,'34',NULL),
('door','Primary strike','12','EMDL','Inactive-leaf strike preparations',false,true,'34',NULL),
('door','Primary strike','12','OBS','Inactive-leaf strike preparations',false,true,'34',NULL),
('door','Primary strike','12','RSTK','Inactive-leaf strike preparations',false,true,'34',NULL),
('door','Primary strike','12','ICS2','Inactive-leaf strike preparations',false,true,'34',NULL),
('door','Hardware location','13','PIO','Pioneer standard / S-series / special / template-defined location',false,false,'35',NULL),
('door','Hardware location','13','S--','Pioneer standard / S-series / special / template-defined location',false,false,'35',NULL),
('door','Hardware location','13','SPL','Pioneer standard / S-series / special / template-defined location',false,false,'35',NULL),
('door','Hardware location','13','device-specific','Pioneer standard / S-series / special / template-defined location',false,false,'35',NULL),
('door','Secondary lock','14','CDL','Cylindrical / mortise / 1-inch-edge / special deadlock prep',true,true,'35',NULL),
('door','Secondary lock','14','MDL','Cylindrical / mortise / 1-inch-edge / special deadlock prep',true,true,'35',NULL),
('door','Secondary lock','14','C160','Cylindrical / mortise / 1-inch-edge / special deadlock prep',true,true,'35',NULL),
('door','Secondary lock','14','SPL','Cylindrical / mortise / 1-inch-edge / special deadlock prep',true,true,'35',NULL),
('door','Secondary strike','14','478N','No-lip deadlock strike or special strike',false,true,'35',NULL),
('door','Secondary strike','14','234N','No-lip deadlock strike or special strike',false,true,'35',NULL),
('door','Secondary strike','14','SPL','No-lip deadlock strike or special strike',false,true,'35',NULL),
('door','Hand','15','RH','Standard door handing codes',false,false,'35',NULL),
('door','Hand','15','RHR','Standard door handing codes',false,false,'35',NULL),
('door','Hand','15','LH','Standard door handing codes',false,false,'35',NULL),
('door','Hand','15','LHR','Standard door handing codes',false,false,'35',NULL),
('door','Hand','15','NH','Standard door handing codes',false,false,'35',NULL),
('door','Undercut','16','5','Standard, typical, special, or zero undercut',false,false,'35',NULL),
('door','Undercut','16','8','Standard, typical, special, or zero undercut',false,false,'35',NULL),
('door','Undercut','16','3','Standard, typical, special, or zero undercut',false,false,'35',NULL),
('door','Undercut','16','4','Standard, typical, special, or zero undercut',false,false,'35',NULL),
('door','Undercut','16','SPL','Standard, typical, special, or zero undercut',false,false,'35',NULL),
('door','Undercut','16','0','Standard, typical, special, or zero undercut',false,false,'35',NULL),
('door','Undercut','16','0','Standard, typical, special, or zero undercut',false,false,'35',NULL),
('door','Label','17','L','Label required / no label',false,false,'35',NULL),
('door','Label','17','N','Label required / no label',false,false,'35',NULL),
('door','Caps','18-19','STS','Single top/bottom screw, weld, or weather-tight cap',false,false,'36',NULL),
('door','Caps','18-19','SBS','Single top/bottom screw, weld, or weather-tight cap',false,false,'36',NULL),
('door','Caps','18-19','STW','Single top/bottom screw, weld, or weather-tight cap',false,false,'36',NULL),
('door','Caps','18-19','SBW','Single top/bottom screw, weld, or weather-tight cap',false,false,'36',NULL),
('door','Caps','18-19','STF','Single top/bottom screw, weld, or weather-tight cap',false,false,'36',NULL),
('door','Caps','18-19','SBF','Single top/bottom screw, weld, or weather-tight cap',false,false,'36',NULL),
('door','Caps','18-19','STBS','Top-and-bottom screw, weld, or weather-tight caps',false,false,'36',NULL),
('door','Caps','18-19','STBW','Top-and-bottom screw, weld, or weather-tight caps',false,false,'36',NULL),
('door','Caps','18-19','STBF','Top-and-bottom screw, weld, or weather-tight caps',false,false,'36',NULL),
('door','Hinge','20','NOHNG','No prep and butt-hinge sizes/weights',false,false,'36',NULL),
('door','Hinge','20','350','No prep and butt-hinge sizes/weights',false,false,'36',NULL),
('door','Hinge','20','400','No prep and butt-hinge sizes/weights',false,false,'36',NULL),
('door','Hinge','20','450','No prep and butt-hinge sizes/weights',false,false,'36',NULL),
('door','Hinge','20','500','No prep and butt-hinge sizes/weights',false,false,'36',NULL),
('door','Hinge','20','450HW','No prep and butt-hinge sizes/weights',false,false,'36',NULL),
('door','Hinge','20','500HW','No prep and butt-hinge sizes/weights',false,false,'36',NULL),
('door','Continuous hinge','20','CONH','Continuous hinge reinforced / no reinforcement / universal C-series',true,true,'36',NULL),
('door','Continuous hinge','20','CONN','Continuous hinge reinforced / no reinforcement / universal C-series',true,true,'36',NULL),
('door','Continuous hinge','20','CONU','Continuous hinge reinforced / no reinforcement / universal C-series',true,true,'36',NULL),
('door','Pivot','20','PIVOT','Top-bottom pivot or pocket pivot',true,true,'36',NULL),
('door','Pivot','20','POCKT','Top-bottom pivot or pocket pivot',true,true,'36',NULL),
('door','Special hinge','20','DM67H','Large, rounded, spring, invisible, or anchor hinge prep',true,false,'36',NULL),
('door','Special hinge','20','RNDCH','Large, rounded, spring, invisible, or anchor hinge prep',true,false,'36',NULL),
('door','Special hinge','20','SASPH','Large, rounded, spring, invisible, or anchor hinge prep',true,false,'36',NULL),
('door','Special hinge','20','DASPH','Large, rounded, spring, invisible, or anchor hinge prep',true,false,'36',NULL),
('door','Special hinge','20','INVH','Large, rounded, spring, invisible, or anchor hinge prep',true,false,'36',NULL),
('door','Special hinge','20','ANCHR','Large, rounded, spring, invisible, or anchor hinge prep',true,false,'36',NULL),
('door','Hinge quantity','21','1-7','Standard height-based quantity or each additional hinge',false,false,'37',NULL),
('door','Hinge quantity','21','+1','Standard height-based quantity or each additional hinge',false,false,'37',NULL),
('door','Hinge location','22','PIO','Pioneer / S-series / special hardware location',false,false,'37',NULL),
('door','Hinge location','22','S--','Pioneer / S-series / special hardware location',false,false,'37',NULL),
('door','Hinge location','22','SPL','Pioneer / S-series / special hardware location',false,false,'37',NULL),
('door','Closer','23','STD','Surface, overhead, concealed, smoke-check, or labeled-no-closer acknowledgement',false,false,'37',NULL),
('door','Closer','23','PAC','Surface, overhead, concealed, smoke-check, or labeled-no-closer acknowledgement',false,false,'37',NULL),
('door','Closer','23','SOH','Surface, overhead, concealed, smoke-check, or labeled-no-closer acknowledgement',false,false,'37',NULL),
('door','Closer','23','MOH','Surface, overhead, concealed, smoke-check, or labeled-no-closer acknowledgement',false,false,'37',NULL),
('door','Closer','23','COC','Surface, overhead, concealed, smoke-check, or labeled-no-closer acknowledgement',false,false,'37',NULL),
('door','Closer','23','SCC','Surface, overhead, concealed, smoke-check, or labeled-no-closer acknowledgement',false,false,'37',NULL),
('door','Closer','23','FRNC','Surface, overhead, concealed, smoke-check, or labeled-no-closer acknowledgement',false,false,'37',NULL),
('door','Bolt','24','FB','Flush, automatic, special, surface bolt, magnetic hold, or top-only prep',false,true,'37',NULL),
('door','Bolt','24','AFB','Flush, automatic, special, surface bolt, magnetic hold, or top-only prep',false,true,'37',NULL),
('door','Bolt','24','AFSP','Flush, automatic, special, surface bolt, magnetic hold, or top-only prep',false,true,'37',NULL),
('door','Bolt','24','SBR','Flush, automatic, special, surface bolt, magnetic hold, or top-only prep',false,true,'37',NULL),
('door','Bolt','24','EMH','Flush, automatic, special, surface bolt, magnetic hold, or top-only prep',false,true,'37',NULL),
('door','Bolt','24','AFBT','Flush, automatic, special, surface bolt, magnetic hold, or top-only prep',false,true,'37',NULL),
('door','Edge','25','BVLD','Door-edge and rabbeted-edge construction',false,false,'38',NULL),
('door','Edge','25','SQRE','Door-edge and rabbeted-edge construction',false,false,'38',NULL),
('door','Edge','25','BLN(B','Door-edge and rabbeted-edge construction',false,false,'38',NULL),
('door','Edge','25','L','Door-edge and rabbeted-edge construction',false,false,'38',NULL),
('door','Edge','25','H)','Door-edge and rabbeted-edge construction',false,false,'38',NULL),
('door','Edge','25','BVLD(L)','Door-edge and rabbeted-edge construction',false,false,'38',NULL),
('door','Edge','25','RSA','Door-edge and rabbeted-edge construction',false,false,'38',NULL),
('door','Edge','25','RSB','Door-edge and rabbeted-edge construction',false,false,'38',NULL),
('door','Edge','25','RTA','Door-edge and rabbeted-edge construction',false,false,'38',NULL),
('door','Edge','25','RTB','Door-edge and rabbeted-edge construction',false,false,'38',NULL),
('door','Core/construction','25','WK','Wicket; polystyrene or polyurethane between stiffeners',false,true,'38',NULL),
('door','Core/construction','25','PCBS','Wicket; polystyrene or polyurethane between stiffeners',false,true,'38',NULL),
('door','Core/construction','25','UCBS','Wicket; polystyrene or polyurethane between stiffeners',false,true,'38',NULL),
('door','Dutch','25','DTCH','Dutch door and Dutch shelf',false,true,'38',NULL),
('door','Dutch','25','DTS','Dutch door and Dutch shelf',false,true,'38',NULL),
('door','Monorail','25','MNO','Monorail cutout / gasket',false,true,'38',NULL),
('door','Monorail','25','MRG','Monorail cutout / gasket',false,true,'38',NULL),
('door','Lead lined','25','LLDW','Lead-lined door with welded/weather-tight caps and lead astragal',false,true,'38',NULL),
('door','Lead lined','25','LLDF','Lead-lined door with welded/weather-tight caps and lead astragal',false,true,'38',NULL),
('door','Lead lined','25','LLA','Lead-lined door with welded/weather-tight caps and lead astragal',false,true,'38',NULL),
('door','Hinge/electric','25','HFH','High-frequency hinge, pivot, electrified preps and conduit',true,false,'39',NULL),
('door','Hinge/electric','25','IPV','High-frequency hinge, pivot, electrified preps and conduit',true,false,'39',NULL),
('door','Hinge/electric','25','ELH','High-frequency hinge, pivot, electrified preps and conduit',true,false,'39',NULL),
('door','Hinge/electric','25','PTP','High-frequency hinge, pivot, electrified preps and conduit',true,false,'39',NULL),
('door','Hinge/electric','25','CN4','High-frequency hinge, pivot, electrified preps and conduit',true,false,'39',NULL),
('door','Hinge/electric','25','MAG','High-frequency hinge, pivot, electrified preps and conduit',true,false,'39',NULL),
('door','Hinge/electric','25','DPS','High-frequency hinge, pivot, electrified preps and conduit',true,false,'39',NULL),
('door','Lock/operation','25','BSS','Special backset, operator, bumper, mail slot, viewer, hospital, roller, fire latch',true,false,'39',NULL),
('door','Lock/operation','25','AOP','Special backset, operator, bumper, mail slot, viewer, hospital, roller, fire latch',true,false,'39',NULL),
('door','Lock/operation','25','RSB','Special backset, operator, bumper, mail slot, viewer, hospital, roller, fire latch',true,false,'39',NULL),
('door','Lock/operation','25','MS','Special backset, operator, bumper, mail slot, viewer, hospital, roller, fire latch',true,false,'39',NULL),
('door','Lock/operation','25','VW','Special backset, operator, bumper, mail slot, viewer, hospital, roller, fire latch',true,false,'39',NULL),
('door','Lock/operation','25','VW2','Special backset, operator, bumper, mail slot, viewer, hospital, roller, fire latch',true,false,'39',NULL),
('door','Lock/operation','25','HL','Special backset, operator, bumper, mail slot, viewer, hospital, roller, fire latch',true,false,'39',NULL),
('door','Lock/operation','25','RL','Special backset, operator, bumper, mail slot, viewer, hospital, roller, fire latch',true,false,'39',NULL),
('door','Lock/operation','25','FL','Special backset, operator, bumper, mail slot, viewer, hospital, roller, fire latch',true,false,'39',NULL),
('door','Door bottom','25','MDB','Mortised / surface-applied door-bottom prep',true,true,'39',NULL),
('door','Door bottom','25','SDB','Mortised / surface-applied door-bottom prep',true,true,'39',NULL),
('door','Paint','25','NOPP','No prime paint on galvannealed door',false,false,'39',NULL),
('door','Marking','26','Tag','Identification and floor segregation',false,false,'37',NULL),
('door','Marking','26','mark','Identification and floor segregation',false,false,'37',NULL),
('door','Marking','26','segregate by floor','Identification and floor segregation',false,false,'37',NULL),
('frame','Series','3','F','Standard masonry / drywall series',false,false,'44-51, 59',NULL),
('frame','Series','3','DW','Standard masonry / drywall series',false,false,'44-51, 59',NULL),
('frame','Borrowed lite','3','F-BL','Masonry / drywall borrowed-lite series',false,false,'52, 59',NULL),
('frame','Borrowed lite','3','DWBL','Masonry / drywall borrowed-lite series',false,false,'52, 59',NULL),
('frame','Special series','3','WF','UniSeal, split frame, or stick material',false,false,'45-53, 59-61',NULL),
('frame','Special series','3','SPF','UniSeal, split frame, or stick material',false,false,'45-53, 59-61',NULL),
('frame','Special series','3','STK','UniSeal, split frame, or stick material',false,false,'45-53, 59-61',NULL),
('frame','Specialty series','3','F50','Windstorm, sound, FEMA, blast, bullet-resistant',false,true,'59, 87-101',NULL),
('frame','Specialty series','3','F70','Windstorm, sound, FEMA, blast, bullet-resistant',false,true,'59, 87-101',NULL),
('frame','Specialty series','3','FST','Windstorm, sound, FEMA, blast, bullet-resistant',false,true,'59, 87-101',NULL),
('frame','Specialty series','3','FEMA','Windstorm, sound, FEMA, blast, bullet-resistant',false,true,'59, 87-101',NULL),
('frame','Specialty series','3','SBR','Windstorm, sound, FEMA, blast, bullet-resistant',false,true,'59, 87-101',NULL),
('frame','Specialty series','3','BR752','Windstorm, sound, FEMA, blast, bullet-resistant',false,true,'59, 87-101',NULL),
('frame','Gauge','4','18','Frame material gauge',false,false,'59',NULL),
('frame','Gauge','4','16','Frame material gauge',false,false,'59',NULL),
('frame','Gauge','4','14','Frame material gauge',false,false,'59',NULL),
('frame','Gauge','4','12','Frame material gauge',false,false,'59',NULL),
('frame','Material','5','C','Cold rolled steel / galvannealed',false,false,'59',NULL),
('frame','Material','5','G','Cold rolled steel / galvannealed',false,false,'59',NULL),
('frame','Door thickness/rabbet','6','4','1-3/4 / 1-3/8 / special hardware rabbet',false,false,'60',NULL),
('frame','Door thickness/rabbet','6','8','1-3/4 / 1-3/8 / special hardware rabbet',false,false,'60',NULL),
('frame','Door thickness/rabbet','6','T2','1-3/4 / 1-3/8 / special hardware rabbet',false,false,'60',NULL),
('frame','Rabbet/profile','7','ER','Equal, unequal, single rabbet, cased opening, double egress',false,false,'60',NULL),
('frame','Rabbet/profile','7','UR','Equal, unequal, single rabbet, cased opening, double egress',false,false,'60',NULL),
('frame','Rabbet/profile','7','SR','Equal, unequal, single rabbet, cased opening, double egress',false,false,'60',NULL),
('frame','Rabbet/profile','7','CO','Equal, unequal, single rabbet, cased opening, double egress',false,false,'60',NULL),
('frame','Rabbet/profile','7','DE','Equal, unequal, single rabbet, cased opening, double egress',false,false,'60',NULL),
('frame','Unit type','8','3S','Three-sided single, three-sided pair, four-sided borrowed lite',false,false,'60',NULL),
('frame','Unit type','8','3P','Three-sided single, three-sided pair, four-sided borrowed lite',false,false,'60',NULL),
('frame','Unit type','8','4S','Three-sided single, three-sided pair, four-sided borrowed lite',false,false,'60',NULL),
('frame','Component type','8','H','Head, pair head, hinge jamb, strike jamb, blank jamb, borrowed-lite jamb',false,false,'60-61',NULL),
('frame','Component type','8','PH','Head, pair head, hinge jamb, strike jamb, blank jamb, borrowed-lite jamb',false,false,'60-61',NULL),
('frame','Component type','8','HJ','Head, pair head, hinge jamb, strike jamb, blank jamb, borrowed-lite jamb',false,false,'60-61',NULL),
('frame','Component type','8','SJ','Head, pair head, hinge jamb, strike jamb, blank jamb, borrowed-lite jamb',false,false,'60-61',NULL),
('frame','Component type','8','BJ','Head, pair head, hinge jamb, strike jamb, blank jamb, borrowed-lite jamb',false,false,'60-61',NULL),
('frame','Component type','8','BLJ','Head, pair head, hinge jamb, strike jamb, blank jamb, borrowed-lite jamb',false,false,'60-61',NULL),
('frame','Stick component','8','UNIT','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','FBJ','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','FHJ','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','FSJ','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','FM2','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','FM4','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','SHM','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','DHM','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','HSM','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','FPS','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','FPN','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','FCP','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','FI2','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','SHI','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','SSI','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','DHI','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','DSI','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','HIS','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','BJ4','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','BJ6','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','BJ8','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','SS4','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','SS6','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','SS8','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','FSC','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','CP2','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','CP3','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Stick component','8','C45','Stick and special-unit component catalog',false,false,'61, 79-84',NULL),
('frame','Split component','8','HJC','Split-frame component types',false,false,'53, 61',NULL),
('frame','Split component','8','SJC','Split-frame component types',false,false,'53, 61',NULL),
('frame','Split component','8','VJC','Split-frame component types',false,false,'53, 61',NULL),
('frame','Split component','8','HC','Split-frame component types',false,false,'53, 61',NULL),
('frame','Split component','8','VHC','Split-frame component types',false,false,'53, 61',NULL),
('frame','Jamb depth','9','SPJD','Special jamb depth',false,false,'62-63',NULL),
('frame','Special size','10-11','SW','Special width / height and oversized components',false,false,'62-63',NULL),
('frame','Special size','10-11','SH','Special width / height and oversized components',false,false,'62-63',NULL),
('frame','Primary strike','12','478','Standard, blank, electric, applied/trim, emergency, interconnected, no-lip, special strikes',false,true,'64',NULL),
('frame','Primary strike','12','234','Standard, blank, electric, applied/trim, emergency, interconnected, no-lip, special strikes',false,true,'64',NULL),
('frame','Primary strike','12','BLNK','Standard, blank, electric, applied/trim, emergency, interconnected, no-lip, special strikes',false,true,'64',NULL),
('frame','Primary strike','12','ESTK','Standard, blank, electric, applied/trim, emergency, interconnected, no-lip, special strikes',false,true,'64',NULL),
('frame','Primary strike','12','SASR','Standard, blank, electric, applied/trim, emergency, interconnected, no-lip, special strikes',false,true,'64',NULL),
('frame','Primary strike','12','TASR','Standard, blank, electric, applied/trim, emergency, interconnected, no-lip, special strikes',false,true,'64',NULL),
('frame','Primary strike','12','EMDL','Standard, blank, electric, applied/trim, emergency, interconnected, no-lip, special strikes',false,true,'64',NULL),
('frame','Primary strike','12','ICS2','Standard, blank, electric, applied/trim, emergency, interconnected, no-lip, special strikes',false,true,'64',NULL),
('frame','Primary strike','12','234N','Standard, blank, electric, applied/trim, emergency, interconnected, no-lip, special strikes',false,true,'64',NULL),
('frame','Primary strike','12','478N','Standard, blank, electric, applied/trim, emergency, interconnected, no-lip, special strikes',false,true,'64',NULL),
('frame','Primary strike','12','350N','Standard, blank, electric, applied/trim, emergency, interconnected, no-lip, special strikes',false,true,'64',NULL),
('frame','Primary strike','12','SPL','Standard, blank, electric, applied/trim, emergency, interconnected, no-lip, special strikes',false,true,'64',NULL),
('frame','Strike location','13','PIO','Pioneer, S-series, or special strike location',false,false,'64',NULL),
('frame','Strike location','13','S--','Pioneer, S-series, or special strike location',false,false,'64',NULL),
('frame','Strike location','13','SPL','Pioneer, S-series, or special strike location',false,false,'64',NULL),
('frame','Secondary strike','14','234N','Secondary/deadlock strike preparations',false,true,'64',NULL),
('frame','Secondary strike','14','478N','Secondary/deadlock strike preparations',false,true,'64',NULL),
('frame','Secondary strike','14','350N','Secondary/deadlock strike preparations',false,true,'64',NULL),
('frame','Secondary strike','14','SPL','Secondary/deadlock strike preparations',false,true,'64',NULL),
('frame','Secondary strike','14','SASR','Secondary/deadlock strike preparations',false,true,'64',NULL),
('frame','Hand','15','RH','Frame hand, pair active leaf, or double acting',false,false,'64',NULL),
('frame','Hand','15','LH','Frame hand, pair active leaf, or double acting',false,false,'64',NULL),
('frame','Hand','15','NH','Frame hand, pair active leaf, or double acting',false,false,'64',NULL),
('frame','Hand','15','RHA','Frame hand, pair active leaf, or double acting',false,false,'64',NULL),
('frame','Hand','15','LHA','Frame hand, pair active leaf, or double acting',false,false,'64',NULL),
('frame','Hand','15','DA','Frame hand, pair active leaf, or double acting',false,false,'64',NULL),
('frame','Face','16','2H2J','Standard and special face/head combinations',false,false,'64-65',NULL),
('frame','Face','16','4H2J','Standard and special face/head combinations',false,false,'64-65',NULL),
('frame','Face','16','6H2J','Standard and special face/head combinations',false,false,'64-65',NULL),
('frame','Face','16','2FC','Standard and special face/head combinations',false,false,'64-65',NULL),
('frame','Face','16','4FC','Standard and special face/head combinations',false,false,'64-65',NULL),
('frame','Face','16','6FC','Standard and special face/head combinations',false,false,'64-65',NULL),
('frame','Face','16','SPL','Standard and special face/head combinations',false,false,'64-65',NULL),
('frame','Backbend','16','DRTN','Double return, hemmed, caulking groove, shadow line',false,false,'65',NULL),
('frame','Backbend','16','HMBB','Double return, hemmed, caulking groove, shadow line',false,false,'65',NULL),
('frame','Backbend','16','CGBB','Double return, hemmed, caulking groove, shadow line',false,false,'65',NULL),
('frame','Backbend','16','SLBB','Double return, hemmed, caulking groove, shadow line',false,false,'65',NULL),
('frame','Label','17','L','Label required / no label',false,false,'66',NULL),
('frame','Label','17','N','Label required / no label',false,false,'66',NULL),
('frame','Assembly','18','FW','Face weld, continuous throat weld, knocked down, others-to-weld',false,false,'66',NULL),
('frame','Assembly','18','CW','Face weld, continuous throat weld, knocked down, others-to-weld',false,false,'66',NULL),
('frame','Assembly','18','KD','Face weld, continuous throat weld, knocked down, others-to-weld',false,false,'66',NULL),
('frame','Assembly','18','KDC','Face weld, continuous throat weld, knocked down, others-to-weld',false,false,'66',NULL),
('frame','Anchor family','19','MAS','Masonry, wood stud, steel stud, existing opening, punch-and-dimple, drywall anchors',false,false,'66',NULL),
('frame','Anchor family','19','WS','Masonry, wood stud, steel stud, existing opening, punch-and-dimple, drywall anchors',false,false,'66',NULL),
('frame','Anchor family','19','STS','Masonry, wood stud, steel stud, existing opening, punch-and-dimple, drywall anchors',false,false,'66',NULL),
('frame','Anchor family','19','EO','Masonry, wood stud, steel stud, existing opening, punch-and-dimple, drywall anchors',false,false,'66',NULL),
('frame','Anchor family','19','P&D','Masonry, wood stud, steel stud, existing opening, punch-and-dimple, drywall anchors',false,false,'66',NULL),
('frame','Anchor family','19','DWCS','Masonry, wood stud, steel stud, existing opening, punch-and-dimple, drywall anchors',false,false,'66',NULL),
('frame','Anchor family','19','DWBH','Masonry, wood stud, steel stud, existing opening, punch-and-dimple, drywall anchors',false,false,'66',NULL),
('frame','Anchor subtype','19','Y&S','Specific welded-in or prepared anchor construction',false,false,'66',NULL),
('frame','Anchor subtype','19','WSSA','Specific welded-in or prepared anchor construction',false,false,'66',NULL),
('frame','Anchor subtype','19','ZCLIP','Specific welded-in or prepared anchor construction',false,false,'66',NULL),
('frame','Anchor subtype','19','SSHH','Specific welded-in or prepared anchor construction',false,false,'66',NULL),
('frame','Anchor subtype','19','STHH','Specific welded-in or prepared anchor construction',false,false,'66',NULL),
('frame','Anchor subtype','19','DE16','Specific welded-in or prepared anchor construction',false,false,'66',NULL),
('frame','Anchor subtype','19','DE12','Specific welded-in or prepared anchor construction',false,false,'66',NULL),
('frame','Anchor subtype','19','2EB','Specific welded-in or prepared anchor construction',false,false,'66',NULL),
('frame','Anchor subtype','19','EOBF','Specific welded-in or prepared anchor construction',false,false,'66',NULL),
('frame','Anchor subtype','19','CHPP','Specific welded-in or prepared anchor construction',false,false,'66',NULL),
('frame','Anchor subtype','19','EOPP','Specific welded-in or prepared anchor construction',false,false,'66',NULL),
('frame','Anchor subtype','19','DE+EOPP','Specific welded-in or prepared anchor construction',false,false,'66',NULL),
('frame','Hinge','20','NOHNG','No prep and butt-hinge families',false,false,'67',NULL),
('frame','Hinge','20','350','No prep and butt-hinge families',false,false,'67',NULL),
('frame','Hinge','20','400','No prep and butt-hinge families',false,false,'67',NULL),
('frame','Hinge','20','450','No prep and butt-hinge families',false,false,'67',NULL),
('frame','Hinge','20','500','No prep and butt-hinge families',false,false,'67',NULL),
('frame','Hinge','20','450HW','No prep and butt-hinge families',false,false,'67',NULL),
('frame','Hinge','20','500HW','No prep and butt-hinge families',false,false,'67',NULL),
('frame','Hinge','20','DD45','No prep and butt-hinge families',false,false,'67',NULL),
('frame','Hinge','20','DD50','No prep and butt-hinge families',false,false,'67',NULL),
('frame','Continuous hinge','20','CONH','Continuous hinge reinforcement in rabbet / face',true,true,'67',NULL),
('frame','Continuous hinge','20','CONHF','Continuous hinge reinforcement in rabbet / face',true,true,'67',NULL),
('frame','Pivot/special hinge','20','PIVOT','Pivot, Eliason, large, rounded, invisible, anchor, spring hinge',true,false,'67',NULL),
('frame','Pivot/special hinge','20','POCKT','Pivot, Eliason, large, rounded, invisible, anchor, spring hinge',true,false,'67',NULL),
('frame','Pivot/special hinge','20','ELIAS','Pivot, Eliason, large, rounded, invisible, anchor, spring hinge',true,false,'67',NULL),
('frame','Pivot/special hinge','20','DM67H','Pivot, Eliason, large, rounded, invisible, anchor, spring hinge',true,false,'67',NULL),
('frame','Pivot/special hinge','20','RNDCH','Pivot, Eliason, large, rounded, invisible, anchor, spring hinge',true,false,'67',NULL),
('frame','Pivot/special hinge','20','INVH','Pivot, Eliason, large, rounded, invisible, anchor, spring hinge',true,false,'67',NULL),
('frame','Pivot/special hinge','20','ANCHR','Pivot, Eliason, large, rounded, invisible, anchor, spring hinge',true,false,'67',NULL),
('frame','Pivot/special hinge','20','DASPH','Pivot, Eliason, large, rounded, invisible, anchor, spring hinge',true,false,'67',NULL),
('frame','Hinge quantity','21','1-7','Standard height-based quantity or each additional hinge',false,false,'68',NULL),
('frame','Hinge quantity','21','+1','Standard height-based quantity or each additional hinge',false,false,'68',NULL),
('frame','Hinge location','22','PIO','Pioneer, S-series, or special hinge location',false,false,'68',NULL),
('frame','Hinge location','22','S--','Pioneer, S-series, or special hinge location',false,false,'68',NULL),
('frame','Hinge location','22','SPL','Pioneer, S-series, or special hinge location',false,false,'68',NULL),
('frame','Closer','23','NOCL','Closer, holder, sleeve, full-width, bracket, and coordinator reinforcements',false,false,'68',NULL),
('frame','Closer','23','FRNC','Closer, holder, sleeve, full-width, bracket, and coordinator reinforcements',false,false,'68',NULL),
('frame','Closer','23','REG','Closer, holder, sleeve, full-width, bracket, and coordinator reinforcements',false,false,'68',NULL),
('frame','Closer','23','PAC','Closer, holder, sleeve, full-width, bracket, and coordinator reinforcements',false,false,'68',NULL),
('frame','Closer','23','RPC','Closer, holder, sleeve, full-width, bracket, and coordinator reinforcements',false,false,'68',NULL),
('frame','Closer','23','TJC','Closer, holder, sleeve, full-width, bracket, and coordinator reinforcements',false,false,'68',NULL),
('frame','Closer','23','CLSL','Closer, holder, sleeve, full-width, bracket, and coordinator reinforcements',false,false,'68',NULL),
('frame','Closer','23','CLFW','Closer, holder, sleeve, full-width, bracket, and coordinator reinforcements',false,false,'68',NULL),
('frame','Closer','23','PAFW','Closer, holder, sleeve, full-width, bracket, and coordinator reinforcements',false,false,'68',NULL),
('frame','Closer','23','SOHS','Closer, holder, sleeve, full-width, bracket, and coordinator reinforcements',false,false,'68',NULL),
('frame','Closer','23','MOHS','Closer, holder, sleeve, full-width, bracket, and coordinator reinforcements',false,false,'68',NULL),
('frame','Closer','23','COHS','Closer, holder, sleeve, full-width, bracket, and coordinator reinforcements',false,false,'68',NULL),
('frame','Closer','23','BRKT','Closer, holder, sleeve, full-width, bracket, and coordinator reinforcements',false,false,'68',NULL),
('frame','Closer','23','RPTJ','Closer, holder, sleeve, full-width, bracket, and coordinator reinforcements',false,false,'68',NULL),
('frame','Closer','23','TJFW','Closer, holder, sleeve, full-width, bracket, and coordinator reinforcements',false,false,'68',NULL),
('frame','Closer','23','CORF','Closer, holder, sleeve, full-width, bracket, and coordinator reinforcements',false,false,'68',NULL),
('frame','Closer','23','CORS','Closer, holder, sleeve, full-width, bracket, and coordinator reinforcements',false,false,'68',NULL),
('frame','Bolt/top latch','24','NOFB','Flush-bolt, automatic, surface-bolt, CVR, and roller-latch header preparations',false,false,'69',NULL),
('frame','Bolt/top latch','24','FBU','Flush-bolt, automatic, surface-bolt, CVR, and roller-latch header preparations',false,false,'69',NULL),
('frame','Bolt/top latch','24','FBKO','Flush-bolt, automatic, surface-bolt, CVR, and roller-latch header preparations',false,false,'69',NULL),
('frame','Bolt/top latch','24','FBM','Flush-bolt, automatic, surface-bolt, CVR, and roller-latch header preparations',false,false,'69',NULL),
('frame','Bolt/top latch','24','AFBR','Flush-bolt, automatic, surface-bolt, CVR, and roller-latch header preparations',false,false,'69',NULL),
('frame','Bolt/top latch','24','SBRF','Flush-bolt, automatic, surface-bolt, CVR, and roller-latch header preparations',false,false,'69',NULL),
('frame','Bolt/top latch','24','SBRS','Flush-bolt, automatic, surface-bolt, CVR, and roller-latch header preparations',false,false,'69',NULL),
('frame','Bolt/top latch','24','CVRS1','Flush-bolt, automatic, surface-bolt, CVR, and roller-latch header preparations',false,false,'69',NULL),
('frame','Bolt/top latch','24','CVRS2','Flush-bolt, automatic, surface-bolt, CVR, and roller-latch header preparations',false,false,'69',NULL),
('frame','Bolt/top latch','24','RLMS1','Flush-bolt, automatic, surface-bolt, CVR, and roller-latch header preparations',false,false,'69',NULL),
('frame','Bolt/top latch','24','RLMS2','Flush-bolt, automatic, surface-bolt, CVR, and roller-latch header preparations',false,false,'69',NULL),
('frame','Construction','25','THRM','Thermal, UniSeal, pocket, nail-on, hospital, lead, grout-plug, end-cap options',false,false,'69',NULL),
('frame','Construction','25','WF','Thermal, UniSeal, pocket, nail-on, hospital, lead, grout-plug, end-cap options',false,false,'69',NULL),
('frame','Construction','25','PCKT','Thermal, UniSeal, pocket, nail-on, hospital, lead, grout-plug, end-cap options',false,false,'69',NULL),
('frame','Construction','25','NAIL','Thermal, UniSeal, pocket, nail-on, hospital, lead, grout-plug, end-cap options',false,false,'69',NULL),
('frame','Construction','25','HOSP','Thermal, UniSeal, pocket, nail-on, hospital, lead, grout-plug, end-cap options',false,false,'69',NULL),
('frame','Construction','25','LLFC','Thermal, UniSeal, pocket, nail-on, hospital, lead, grout-plug, end-cap options',false,false,'69',NULL),
('frame','Construction','25','LLCO','Thermal, UniSeal, pocket, nail-on, hospital, lead, grout-plug, end-cap options',false,false,'69',NULL),
('frame','Construction','25','GHP','Thermal, UniSeal, pocket, nail-on, hospital, lead, grout-plug, end-cap options',false,false,'69',NULL),
('frame','Construction','25','ECWF','Thermal, UniSeal, pocket, nail-on, hospital, lead, grout-plug, end-cap options',false,false,'69',NULL),
('frame','Electrical','25','CND','Conduit, power transfer, electric hinge, door-position, magnetic-switch prep',true,false,'69',NULL),
('frame','Electrical','25','PTP','Conduit, power transfer, electric hinge, door-position, magnetic-switch prep',true,false,'69',NULL),
('frame','Electrical','25','ELH','Conduit, power transfer, electric hinge, door-position, magnetic-switch prep',true,false,'69',NULL),
('frame','Electrical','25','DPS','Conduit, power transfer, electric hinge, door-position, magnetic-switch prep',true,false,'69',NULL),
('frame','Electrical','25','MAGS','Conduit, power transfer, electric hinge, door-position, magnetic-switch prep',true,false,'69',NULL),
('frame','Jamb/reinforcement','25','CJ','Communicating, Dutch, dust box, and special hinge reinforcements',false,false,'70',NULL),
('frame','Jamb/reinforcement','25','DTCH','Communicating, Dutch, dust box, and special hinge reinforcements',false,false,'70',NULL),
('frame','Jamb/reinforcement','25','DBDW','Communicating, Dutch, dust box, and special hinge reinforcements',false,false,'70',NULL),
('frame','Jamb/reinforcement','25','FWHR','Communicating, Dutch, dust box, and special hinge reinforcements',false,false,'70',NULL),
('frame','Jamb/reinforcement','25','FHHR','Communicating, Dutch, dust box, and special hinge reinforcements',false,false,'70',NULL),
('frame','Jamb/reinforcement','25','INPV','Communicating, Dutch, dust box, and special hinge reinforcements',false,false,'70',NULL),
('frame','Jamb/reinforcement','25','HFH','Communicating, Dutch, dust box, and special hinge reinforcements',false,false,'70',NULL),
('frame','Head/reinforcement','25','SHDR','Head, applied-stop/weatherstrip, mullion, and 12-gauge closer reinforcement',false,false,'70',NULL),
('frame','Head/reinforcement','25','RASW','Head, applied-stop/weatherstrip, mullion, and 12-gauge closer reinforcement',false,false,'70',NULL),
('frame','Head/reinforcement','25','RFHM','Head, applied-stop/weatherstrip, mullion, and 12-gauge closer reinforcement',false,false,'70',NULL),
('frame','Head/reinforcement','25','12GC','Head, applied-stop/weatherstrip, mullion, and 12-gauge closer reinforcement',false,false,'70',NULL),
('frame','Anchoring/base','25','OPFK','Floor knee, adjustable base, no silencers, base holes, reversed floor anchors',false,false,'70',NULL),
('frame','Anchoring/base','25','ADJA','Floor knee, adjustable base, no silencers, base holes, reversed floor anchors',false,false,'70',NULL),
('frame','Anchoring/base','25','NOS','Floor knee, adjustable base, no silencers, base holes, reversed floor anchors',false,false,'70',NULL),
('frame','Anchoring/base','25','BHA','Floor knee, adjustable base, no silencers, base holes, reversed floor anchors',false,false,'70',NULL),
('frame','Anchoring/base','25','RFLA','Floor knee, adjustable base, no silencers, base holes, reversed floor anchors',false,false,'70',NULL),
('frame','Marking/paint','25','BDL','Segregate by floor, special finish, or no prime on galvannealed',false,false,'70',NULL),
('frame','Marking/paint','25','SPLP','Segregate by floor, special finish, or no prime on galvannealed',false,false,'70',NULL),
('frame','Marking/paint','25','NOPP','Segregate by floor, special finish, or no prime on galvannealed',false,false,'70',NULL),
('panel','Series/core','3','H','Lockseam/full-flush honeycomb, polystyrene, polyurethane, or seamless panel',false,false,'24',NULL),
('panel','Series/core','3','HP','Lockseam/full-flush honeycomb, polystyrene, polyurethane, or seamless panel',false,false,'24',NULL),
('panel','Series/core','3','HT','Lockseam/full-flush honeycomb, polystyrene, polyurethane, or seamless panel',false,false,'24',NULL),
('panel','Series/core','3','HF','Lockseam/full-flush honeycomb, polystyrene, polyurethane, or seamless panel',false,false,'24',NULL),
('panel','Series/core','3','CH','Continuous-weld seamless glued-core panel',false,false,'24',NULL),
('panel','Series/core','3','CHP','Continuous-weld seamless glued-core panel',false,false,'24',NULL),
('panel','Series/core','3','CHT','Continuous-weld seamless glued-core panel',false,false,'24',NULL),
('panel','Series/core','3','C','Continuous-weld steel-stiffened panel',false,false,'24',NULL),
('panel','Series/core','3','LAM','5/8-inch laminated panel',false,false,'24',NULL),
('panel','Gauge','4','16','16-gauge material adder over base',false,false,'24',NULL),
('panel','Material','5','CRS','Cold rolled included / galvannealed adder',false,false,'24',NULL),
('panel','Material','5','G','Cold rolled included / galvannealed adder',false,false,'24',NULL),
('panel','Bottom','5','RTA','Rabbet bottom Type A / Type B',false,false,'24',NULL),
('panel','Bottom','5','RTB','Rabbet bottom Type A / Type B',false,false,'24',NULL),
('panel','Closer','23','PAC','Regular or parallel-arm closer reinforcement',false,false,'24',NULL),
('panel','Strike','24','VR','Vertical-rod strike / flush-bolt strike preparation',false,true,'24',NULL),
('panel','Strike','24','FB','Vertical-rod strike / flush-bolt strike preparation',false,true,'24',NULL),
('panel','Install kit','25','A','No-transom-bar attachment kits',false,false,'25',NULL),
('panel','Install kit','25','B','No-transom-bar attachment kits',false,false,'25',NULL),
('panel','Install kit','25','C','No-transom-bar attachment kits',false,false,'25',NULL),
('panel','Install kit','25','D','No-transom-bar attachment kits',false,false,'25',NULL),
('panel','Install kit','25','E','With-transom-bar attachment kits',false,false,'25',NULL),
('panel','Install kit','25','F','With-transom-bar attachment kits',false,false,'25',NULL),
('panel','Install kit','25','G','With-transom-bar attachment kits',false,false,'25',NULL),
('panel','Install kit','25','H','With-transom-bar attachment kits',false,false,'25',NULL),
('panel','Install kit','25','J','Labeled transom panel welded-channel kits',false,false,'25',NULL),
('panel','Install kit','25','K','Labeled transom panel welded-channel kits',false,false,'25',NULL),
('panel','Install kit','25','L','Labeled transom panel welded-channel kits',false,false,'25',NULL),
('panel','Install kit','25','M','UL moulding / non-labeled removable moulding',false,false,'25',NULL),
('panel','Install kit','25','NL','UL moulding / non-labeled removable moulding',false,false,'25',NULL);