INSERT INTO public.product_family (entity_type,family_code,name) VALUES
('door','H','Honeycomb core, lockseam/full-flush; HF adds seamless tack-and-fill edge'),
('door','HF','Honeycomb core, lockseam/full-flush; HF adds seamless tack-and-fill edge'),
('door','HP','Polystyrene core, lockseam/full-flush; HPF seamless'),
('door','HPF','Polystyrene core, lockseam/full-flush; HPF seamless'),
('door','HT','Polyurethane core, lockseam/full-flush; HTF seamless'),
('door','HTF','Polyurethane core, lockseam/full-flush; HTF seamless'),
('door','HR','Temperature-rise core, lockseam/full-flush; HRF seamless'),
('door','HRF','Temperature-rise core, lockseam/full-flush; HRF seamless'),
('door','CH','Continuous-weld seamless glued-core series'),
('door','CHP','Continuous-weld seamless glued-core series'),
('door','CHT','Continuous-weld seamless glued-core series'),
('door','CHR','Continuous-weld seamless glued-core series'),
('door','LW','Steel-stiffened lockseam; LWF seamless'),
('door','LWF','Steel-stiffened lockseam; LWF seamless'),
('door','C','Continuous-weld seamless steel-stiffened door'),
('door','EH','Embossed lockseam honeycomb or polystyrene door; F suffix seamless'),
('door','EHF','Embossed lockseam honeycomb or polystyrene door; F suffix seamless'),
('door','EP','Embossed lockseam honeycomb or polystyrene door; F suffix seamless'),
('door','EPF','Embossed lockseam honeycomb or polystyrene door; F suffix seamless'),
('door','W50','Piocane windstorm door'),
('door','W70','Piocane windstorm door'),
('door','FEMA','FEMA 361 C-series door'),
('door','STC','Piosonic sound-rated complete unit'),
('door','SBR','Blast-resistant or bullet-resistant door'),
('door','BR752','Blast-resistant or bullet-resistant door'),
('frame','F','Standard masonry / drywall series'),
('frame','DW','Standard masonry / drywall series'),
('frame','F-BL','Masonry / drywall borrowed-lite series'),
('frame','DWBL','Masonry / drywall borrowed-lite series'),
('frame','WF','UniSeal, split frame, or stick material'),
('frame','SPF','UniSeal, split frame, or stick material'),
('frame','STK','UniSeal, split frame, or stick material'),
('frame','F50','Windstorm, sound, FEMA, blast, bullet-resistant'),
('frame','F70','Windstorm, sound, FEMA, blast, bullet-resistant'),
('frame','FST','Windstorm, sound, FEMA, blast, bullet-resistant'),
('frame','FEMA','Windstorm, sound, FEMA, blast, bullet-resistant'),
('frame','SBR','Windstorm, sound, FEMA, blast, bullet-resistant'),
('frame','BR752','Windstorm, sound, FEMA, blast, bullet-resistant');